### ISSUE TITLE
item.iteritems() not compatible with Python3

### ISSUE THREAD

**Issue by bitstreambiker** [jtyr/ansible-motd#1]
Just stumbled on this ... one small change to the Jinja Template.

In Python2, dictionaries have iterkeys(), itervalues(), and iteritems() methods. These methods have been removed in Python3. Playbooks and Jinja2 templates should use dict.keys(), dict.values(), and dict.items() in order to be compatible with both Python2 and Python3.

Cheers,

--Mark

**Comment by jtyr** [comment]
Thanks for opening this issue, @bitstreambiker. Please could you create a PR implementing your suggestion?

**Comment by jtyr** [comment]
This was fixed in 538684103904811f350924f61d5d732305bf989a.
